server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agency-dataentry
    username: root
    password: root

  druid: # 数据库连接池配置
    initial-size: 5 # 初始化连接数
    min-idle: 5 # 最小空闲连接数
    max-active: 20 # 最大连接数AgencyDataEntryService
    filter:
      stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 3000
        connection-stack-trace-enable: true
      slf4j:
        enabled: true
        statement-create-after-log-enabled: false
        statement-close-after-log-enabled: false
        result-set-open-after-log-enabled: false
        result-set-close-after-log-enabled: false
      wall:
        enabled: true
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      login-username: admin
      login-password: admin
    #连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作
    keep-alive: true
    #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle
    pool-prepared-statements: true
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    #在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    max-open-prepared-statements: 100
    #获取连接时最大等待时间，单位毫秒
    max-wait: 60000
    #用来检测连接是否有效的sql 必须是一个查询语句
    validation-query: select 1 from dual
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    test-while-idle: true
    #连接保持空闲而不被驱逐的最小时间,销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
    min-evictable-idle-time-millis: 30000
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true
  #freemarker静态资源配置
  freemarker:
    tempalte-loader-path:
      classpath: /templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .fxl
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.announce.dataentry.operation.entity
  #typeAliasesPackage:
  global-config:
    #数据库相关配置
    db-config:
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: false
      logic-delete-value: -1
      logic-not-delete-value: 0
  #原生配置
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

